{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-chart.secretName" . }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  mysql_password: {{ .Values.mysqlPassword }}
{{- end }}