apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotaions }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 192.168.0.1
  selector:
    {{- include "mysql-chart.selectorLabels" . | nindent 4 }}
